# The 20-question personality test. Each question has 4 options. Each option
# nudges exactly 2 of the 12 skill dimensions: a primary skill (+2 points)
# and a secondary skill (+1 point). The option TEXT never mentions the skill name
# scoring.py turns a list of 20 chosen option indices into a final 0-10
# score per skill dimension. This final vector is the ONLY input to the ML
# model. there is no separate selfrated skill step feeding into it.


QUESTIONS = [
    dict(id="q1",
         text={"en": "When starting a new project, what do you usually do first?",
               "fa": "وقتی یک پروژه جدید را شروع می‌کنید، معمولاً اول چه کاری انجام می‌دهید؟"},
         options=[
             dict(text={"en": "Break it down into smaller, logical steps.",
                         "fa": "آن را به مراحل کوچک‌تر و منطقی تقسیم می‌کنم"},
                  weights={"logical_thinking": 2, "analytical_thinking": 1}),
             dict(text={"en": "Look for a creative or unconventional approach.",
                         "fa": "دنبال یک رویکرد خلاقانه یا غیرمعمول می‌گردم"},
                  weights={"creativity": 2, "curiosity": 1}),
             dict(text={"en": "Discuss it with others to gather different viewpoints.",
                         "fa": "با دیگران درباره‌اش صحبت می‌کنم تا دیدگاه‌های مختلف را بشنوم"},
                  weights={"communication": 2, "learning_speed": 1}),
             dict(text={"en": "Make a detailed plan and checklist.",
                         "fa": "یک برنامه و چک‌لیست دقیق تهیه می‌کنم"},
                  weights={"attention_to_detail": 2, "problem_solving": 1}),
         ]),

    dict(id="q2",
         text={"en": "In a group project, which role do you naturally take?",
               "fa": "در یک پروژه گروهی، معمولاً چه نقشی را به‌طور طبیعی برعهده می‌گیرید؟"},
         options=[
             dict(text={"en": "The one who organizes and leads the team.",
                         "fa": "کسی که تیم را سازمان‌دهی و هدایت می‌کند"},
                  weights={"leadership": 2, "communication": 1}),
             dict(text={"en": "The one who solves the trickiest technical problems.",
                         "fa": "کسی که سخت‌ترین مشکلات فنی را حل می‌کند"},
                  weights={"problem_solving": 2, "mathematics": 1}),
             dict(text={"en": "The one who keeps track of details and deadlines.",
                         "fa": "کسی که مراقب جزئیات و مهلت‌های زمانی است"},
                  weights={"attention_to_detail": 2, "stress_tolerance": 1}),
             dict(text={"en": "The one who comes up with new ideas.",
                         "fa": "کسی که ایده‌های تازه می‌دهد"},
                  weights={"creativity": 2, "curiosity": 1}),
         ]),

    dict(id="q3",
         text={"en": "When you face a difficult problem, what's your first instinct?",
               "fa": "وقتی با یک مشکل سخت روبه‌رو می‌شوید، اولین واکنش شما چیست؟"},
         options=[
             dict(text={"en": "Analyze it step by step using logic.",
                         "fa": "آن را قدم‌به‌قدم و با منطق تحلیل می‌کنم"},
                  weights={"logical_thinking": 2, "analytical_thinking": 1}),
             dict(text={"en": "Try different creative solutions until one works.",
                         "fa": "راه‌حل‌های خلاقانه مختلف را امتحان می‌کنم تا یکی جواب بدهد"},
                  weights={"creativity": 2, "problem_solving": 1}),
             dict(text={"en": "Ask someone with more experience for advice.",
                         "fa": "از کسی که تجربه بیشتری دارد مشورت می‌گیرم"},
                  weights={"communication": 2, "learning_speed": 1}),
             dict(text={"en": "Stay calm and think it through carefully.",
                         "fa": "آرامش خودم را حفظ می‌کنم و با دقت به آن فکر می‌کنم"},
                  weights={"stress_tolerance": 2, "attention_to_detail": 1}),
         ]),

    dict(id="q4",
         text={"en": "How do you prefer to learn something new?",
               "fa": "ترجیح می‌دهید چطور یک چیز جدید را یاد بگیرید؟"},
         options=[
             dict(text={"en": "By reading and studying the theory deeply.",
                         "fa": "با مطالعه عمیق و یادگیری تئوری آن"},
                  weights={"learning_speed": 2, "analytical_thinking": 1}),
             dict(text={"en": "By practicing hands-on right away.",
                         "fa": "با تمرین عملی و بلافاصله شروع کردن"},
                  weights={"learning_speed": 2, "problem_solving": 1}),
             dict(text={"en": "By discussing it with a group or teacher.",
                         "fa": "با بحث و گفت‌وگو در یک گروه یا با یک معلم"},
                  weights={"communication": 2, "teamwork": 1}),
             dict(text={"en": "By exploring it on my own out of curiosity.",
                         "fa": "با کاوش شخصی و از روی کنجکاوی"},
                  weights={"curiosity": 2, "learning_speed": 1}),
         ]),

    dict(id="q5",
         text={"en": "A friend asks for your help with a tricky calculation. You...",
               "fa": "یک دوست از شما کمک می‌خواهد برای یک محاسبه پیچیده. شما..."},
         options=[
             dict(text={"en": "Work through the numbers methodically.",
                         "fa": "با روش و به‌ترتیب با عددها کار می‌کنم"},
                  weights={"mathematics": 2, "logical_thinking": 1}),
             dict(text={"en": "Try to explain it in a simple, relatable way.",
                         "fa": "سعی می‌کنم آن را به شکلی ساده و قابل‌فهم توضیح دهم"},
                  weights={"communication": 2, "mathematics": 1}),
             dict(text={"en": "Look for a pattern to solve it quickly.",
                         "fa": "دنبال یک الگو می‌گردم تا سریع حلش کنم"},
                  weights={"mathematics": 2, "analytical_thinking": 1}),
             dict(text={"en": "Suggest solving it together, step by step.",
                         "fa": "پیشنهاد می‌دهم با هم و قدم‌به‌قدم حلش کنیم"},
                  weights={"teamwork": 2, "mathematics": 1}),
         ]),

    dict(id="q6",
         text={"en": "When working under a tight deadline, you...",
               "fa": "وقتی زیر فشار یک مهلت زمانی کوتاه کار می‌کنید، شما..."},
         options=[
             dict(text={"en": "Stay calm and keep working steadily.",
                         "fa": "آرام می‌مانم و با ثبات به کارم ادامه می‌دهم"},
                  weights={"stress_tolerance": 2, "attention_to_detail": 1}),
             dict(text={"en": "Take charge and reorganize the priorities.",
                         "fa": "کنترل را به دست می‌گیرم و اولویت‌ها را دوباره می‌چینم"},
                  weights={"leadership": 2, "stress_tolerance": 1}),
             dict(text={"en": "Focus intensely on getting the details right.",
                         "fa": "تمام تمرکزم را روی درست بودن جزئیات می‌گذارم"},
                  weights={"attention_to_detail": 2, "problem_solving": 1}),
             dict(text={"en": "Ask teammates to split up the work.",
                         "fa": "از هم‌تیمی‌ها می‌خواهم کار را تقسیم کنیم"},
                  weights={"teamwork": 2, "leadership": 1}),
         ]),

    dict(id="q7",
         text={"en": "You're given a task with no clear instructions. You...",
               "fa": "یک وظیفه بدون دستورالعمل روشن به شما داده شده. شما..."},
         options=[
             dict(text={"en": "Figure out the logical steps yourself.",
                         "fa": "خودم مراحل منطقی آن را پیدا می‌کنم"},
                  weights={"logical_thinking": 2, "problem_solving": 1}),
             dict(text={"en": "Ask questions until it becomes clear.",
                         "fa": "آنقدر سؤال می‌پرسم تا موضوع روشن شود"},
                  weights={"curiosity": 2, "communication": 1}),
             dict(text={"en": "Try a few different approaches to see what works.",
                         "fa": "چند رویکرد مختلف را امتحان می‌کنم تا ببینم کدام جواب می‌دهد"},
                  weights={"creativity": 2, "problem_solving": 1}),
             dict(text={"en": "Research similar situations before starting.",
                         "fa": "قبل از شروع، موقعیت‌های مشابه را بررسی می‌کنم"},
                  weights={"learning_speed": 2, "curiosity": 1}),
         ]),

    dict(id="q8",
         text={"en": "In a debate or discussion, you tend to...",
               "fa": "در یک بحث یا گفت‌وگو، معمولاً چه رفتاری دارید؟"},
         options=[
             dict(text={"en": "Present clear, logical arguments.",
                         "fa": "استدلال‌های روشن و منطقی ارائه می‌دهم"},
                  weights={"logical_thinking": 2, "communication": 1}),
             dict(text={"en": "Listen and try to understand every viewpoint.",
                         "fa": "گوش می‌دهم و سعی می‌کنم هر دیدگاهی را بفهمم"},
                  weights={"communication": 2, "teamwork": 1}),
             dict(text={"en": "Bring up original or unusual angles.",
                         "fa": "زاویه‌های تازه و غیرمعمول را مطرح می‌کنم"},
                  weights={"creativity": 2, "curiosity": 1}),
             dict(text={"en": "Stay focused on the facts and data.",
                         "fa": "تمرکزم را روی واقعیت‌ها و داده‌ها نگه می‌دارم"},
                  weights={"analytical_thinking": 2, "mathematics": 1}),
         ]),

    dict(id="q9",
         text={"en": "When you make a mistake, you usually...",
               "fa": "وقتی اشتباهی مرتکب می‌شوید، معمولاً..."},
         options=[
             dict(text={"en": "Analyze exactly what went wrong.",
                         "fa": "دقیقاً بررسی می‌کنم چه چیزی اشتباه پیش رفته"},
                  weights={"analytical_thinking": 2, "problem_solving": 1}),
             dict(text={"en": "Stay calm and try again.",
                         "fa": "آرام می‌مانم و دوباره تلاش می‌کنم"},
                  weights={"stress_tolerance": 2, "learning_speed": 1}),
             dict(text={"en": "Ask others how they'd handle it.",
                         "fa": "از دیگران می‌پرسم آن‌ها چطور با آن برخورد می‌کردند"},
                  weights={"communication": 2, "teamwork": 1}),
             dict(text={"en": "Note it down carefully to avoid repeating it.",
                         "fa": "با دقت یادداشتش می‌کنم تا دوباره تکرار نشود"},
                  weights={"attention_to_detail": 2, "learning_speed": 1}),
         ]),

    dict(id="q10",
         text={"en": "Your ideal weekend project would be...",
               "fa": "پروژه ایده‌آل شما برای یک آخر هفته چه خواهد بود؟"},
         options=[
             dict(text={"en": "Solving a puzzle or logic challenge.",
                         "fa": "حل یک پازل یا چالش منطقی"},
                  weights={"logical_thinking": 2, "problem_solving": 1}),
             dict(text={"en": "Creating something artistic or original.",
                         "fa": "ساختن یک اثر هنری یا خلاقانه"},
                  weights={"creativity": 2, "curiosity": 1}),
             dict(text={"en": "Organizing an event with friends.",
                         "fa": "برگزاری یک رویداد با دوستان"},
                  weights={"leadership": 2, "teamwork": 1}),
             dict(text={"en": "Learning a completely new skill.",
                         "fa": "یادگیری یک مهارت کاملاً جدید"},
                  weights={"learning_speed": 2, "curiosity": 1}),
         ]),

    dict(id="q11",
         text={"en": "When leading a team, what matters most to you?",
               "fa": "وقتی رهبری یک تیم را برعهده دارید، مهم‌ترین چیز برایتان چیست؟"},
         options=[
             dict(text={"en": "Making sure everyone works well together.",
                         "fa": "اطمینان از اینکه همه به‌خوبی با هم کار می‌کنند"},
                  weights={"leadership": 2, "teamwork": 1}),
             dict(text={"en": "Keeping the plan organized and on schedule.",
                         "fa": "منظم و طبق برنامه نگه داشتن روند کار"},
                  weights={"attention_to_detail": 2, "leadership": 1}),
             dict(text={"en": "Making sure decisions are based on solid reasoning.",
                         "fa": "اطمینان از اینکه تصمیمات بر پایه استدلال محکم است"},
                  weights={"logical_thinking": 2, "leadership": 1}),
             dict(text={"en": "Encouraging new and creative ideas.",
                         "fa": "تشویق ایده‌های تازه و خلاقانه"},
                  weights={"creativity": 2, "leadership": 1}),
         ]),

    dict(id="q12",
         text={"en": "How do you react to sudden, unexpected changes?",
               "fa": "در برابر تغییرات ناگهانی و غیرمنتظره چه واکنشی نشان می‌دهید؟"},
         options=[
             dict(text={"en": "Stay calm and adapt quickly.",
                         "fa": "آرام می‌مانم و سریع خودم را تطبیق می‌دهم"},
                  weights={"stress_tolerance": 2, "problem_solving": 1}),
             dict(text={"en": "Analyze what caused the change first.",
                         "fa": "اول بررسی می‌کنم چه چیزی باعث این تغییر شده"},
                  weights={"analytical_thinking": 2, "logical_thinking": 1}),
             dict(text={"en": "Look at it as a new opportunity.",
                         "fa": "آن را به‌عنوان یک فرصت جدید می‌بینم"},
                  weights={"curiosity": 2, "learning_speed": 1}),
             dict(text={"en": "Carefully reorganize the plan.",
                         "fa": "با دقت برنامه را دوباره سازمان‌دهی می‌کنم"},
                  weights={"attention_to_detail": 2, "leadership": 1}),
         ]),

    dict(id="q13",
         text={"en": "When solving a technical problem, you rely more on...",
               "fa": "برای حل یک مشکل فنی، بیشتر روی کدام تکیه می‌کنید؟"},
         options=[
             dict(text={"en": "Numbers and calculations.",
                         "fa": "اعداد و محاسبات"},
                  weights={"mathematics": 2, "attention_to_detail": 1}),
             dict(text={"en": "Logical, step-by-step reasoning.",
                         "fa": "استدلال منطقی و قدم‌به‌قدم"},
                  weights={"logical_thinking": 2, "problem_solving": 1}),
             dict(text={"en": "Trial and error until it works.",
                         "fa": "امتحان و خطا تا زمانی که جواب بدهد"},
                  weights={"problem_solving": 2, "stress_tolerance": 1}),
             dict(text={"en": "Advice from people who've done it before.",
                         "fa": "مشورت با کسانی که قبلاً این کار را انجام داده‌اند"},
                  weights={"communication": 2, "learning_speed": 1}),
         ]),

    dict(id="q14",
         text={"en": "What kind of tasks give you the most energy?",
               "fa": "چه نوع کارهایی بیشترین انرژی را به شما می‌دهد؟"},
         options=[
             dict(text={"en": "Tasks that require precision and accuracy.",
                         "fa": "کارهایی که نیاز به دقت و درستی بالا دارند"},
                  weights={"attention_to_detail": 2, "mathematics": 1}),
             dict(text={"en": "Tasks that involve talking and connecting with people.",
                         "fa": "کارهایی که شامل گفت‌وگو و ارتباط با افراد است"},
                  weights={"communication": 2, "teamwork": 1}),
             dict(text={"en": "Tasks that let you create something new.",
                         "fa": "کارهایی که به شما اجازه می‌دهد چیزی تازه بسازید"},
                  weights={"creativity": 2, "curiosity": 1}),
             dict(text={"en": "Tasks that challenge you to think and solve.",
                         "fa": "کارهایی که شما را به فکر کردن و حل مسئله وادار می‌کند"},
                  weights={"problem_solving": 2, "analytical_thinking": 1}),
         ]),

    dict(id="q15",
         text={"en": "In a team, you contribute the most by...",
               "fa": "در یک تیم، بیشترین کمک شما معمولاً چیست؟"},
         options=[
             dict(text={"en": "Bringing people together and keeping morale up.",
                         "fa": "کنار هم آوردن افراد و بالا نگه‌داشتن روحیه تیم"},
                  weights={"teamwork": 2, "leadership": 1}),
             dict(text={"en": "Making sure nothing gets overlooked.",
                         "fa": "اطمینان از اینکه هیچ چیزی از قلم نمی‌افتد"},
                  weights={"attention_to_detail": 2, "stress_tolerance": 1}),
             dict(text={"en": "Coming up with new directions.",
                         "fa": "پیشنهاد دادن مسیرهای جدید"},
                  weights={"creativity": 2, "curiosity": 1}),
             dict(text={"en": "Solving the hardest parts of the problem.",
                         "fa": "حل کردن سخت‌ترین بخش‌های مسئله"},
                  weights={"problem_solving": 2, "mathematics": 1}),
         ]),

    dict(id="q16",
         text={"en": "How do you usually make an important decision?",
               "fa": "معمولاً چطور یک تصمیم مهم می‌گیرید؟"},
         options=[
             dict(text={"en": "Weigh the numbers and evidence carefully.",
                         "fa": "با دقت اعداد و شواهد را بررسی می‌کنم"},
                  weights={"mathematics": 2, "analytical_thinking": 1}),
             dict(text={"en": "Trust logical reasoning above all.",
                         "fa": "بیش از هر چیز به استدلال منطقی اعتماد می‌کنم"},
                  weights={"logical_thinking": 2, "analytical_thinking": 1}),
             dict(text={"en": "Consider how it affects the people involved.",
                         "fa": "به تأثیر آن روی افراد درگیر فکر می‌کنم"},
                  weights={"communication": 2, "leadership": 1}),
             dict(text={"en": "Go with the option that feels most innovative.",
                         "fa": "گزینه‌ای را انتخاب می‌کنم که نوآورانه‌تر به نظر برسد"},
                  weights={"creativity": 2, "curiosity": 1}),
         ]),

    dict(id="q17",
         text={"en": "If a plan fails, what's your natural next step?",
               "fa": "اگر یک برنامه شکست بخورد، طبیعی‌ترین قدم بعدی شما چیست؟"},
         options=[
             dict(text={"en": "Stay composed and try a new approach.",
                         "fa": "خونسردی‌ام را حفظ می‌کنم و رویکرد جدیدی امتحان می‌کنم"},
                  weights={"stress_tolerance": 2, "problem_solving": 1}),
             dict(text={"en": "Study exactly what went wrong.",
                         "fa": "دقیقاً بررسی می‌کنم چه چیزی اشتباه بوده"},
                  weights={"analytical_thinking": 2, "learning_speed": 1}),
             dict(text={"en": "Ask the team for feedback and ideas.",
                         "fa": "از تیم بازخورد و ایده می‌خواهم"},
                  weights={"communication": 2, "leadership": 1}),
             dict(text={"en": "Adjust the details and try again carefully.",
                         "fa": "جزئیات را اصلاح می‌کنم و با دقت دوباره امتحان می‌کنم"},
                  weights={"attention_to_detail": 2, "problem_solving": 1}),
         ]),

    dict(id="q18",
         text={"en": "You enjoy tasks most when they...",
               "fa": "چه زمانی بیشترین لذت را از یک کار می‌برید؟"},
         options=[
             dict(text={"en": "Involve solving complex, logical challenges.",
                         "fa": "وقتی شامل حل چالش‌های پیچیده و منطقی باشد"},
                  weights={"logical_thinking": 2, "problem_solving": 1}),
             dict(text={"en": "Let you express creativity.",
                         "fa": "وقتی به من اجازه می‌دهد خلاقیتم را نشان دهم"},
                  weights={"creativity": 2, "curiosity": 1}),
             dict(text={"en": "Involve working closely with others.",
                         "fa": "وقتی شامل همکاری نزدیک با دیگران باشد"},
                  weights={"teamwork": 2, "communication": 1}),
             dict(text={"en": "Require careful attention and precision.",
                         "fa": "وقتی نیاز به دقت و توجه بالا داشته باشد"},
                  weights={"attention_to_detail": 2, "mathematics": 1}),
         ]),

    dict(id="q19",
         text={"en": "How would your friends describe you?",
               "fa": "دوستانتان شما را چطور توصیف می‌کنند؟"},
         options=[
             dict(text={"en": "Reliable and detail-oriented.",
                         "fa": "قابل‌اعتماد و دقیق"},
                  weights={"attention_to_detail": 2, "stress_tolerance": 1}),
             dict(text={"en": "A natural leader.",
                         "fa": "یک رهبر طبیعی"},
                  weights={"leadership": 2, "communication": 1}),
             dict(text={"en": "Curious and always learning something new.",
                         "fa": "کنجکاو و همیشه در حال یادگیری چیزی جدید"},
                  weights={"curiosity": 2, "learning_speed": 1}),
             dict(text={"en": "Creative and full of ideas.",
                         "fa": "خلاق و پر از ایده"},
                  weights={"creativity": 2, "learning_speed": 1}),
         ]),

    dict(id="q20",
         text={"en": "When under pressure, what helps you the most?",
               "fa": "وقتی تحت فشار هستید، چه چیزی بیشترین کمک را به شما می‌کند؟"},
         options=[
             dict(text={"en": "Breaking the problem into logical parts.",
                         "fa": "تقسیم کردن مسئله به بخش‌های منطقی"},
                  weights={"logical_thinking": 2, "problem_solving": 1}),
             dict(text={"en": "Staying calm and focused.",
                         "fa": "آرام و متمرکز ماندن"},
                  weights={"stress_tolerance": 2, "attention_to_detail": 1}),
             dict(text={"en": "Talking it through with someone.",
                         "fa": "صحبت کردن درباره‌اش با یک نفر"},
                  weights={"communication": 2, "teamwork": 1}),
             dict(text={"en": "Trusting your instincts and creativity.",
                         "fa": "اعتماد به غریزه و خلاقیت خودم"},
                  weights={"creativity": 2, "stress_tolerance": 1}),
         ]),
]

assert len(QUESTIONS) == 20, f"Expected 20 questions, got {len(QUESTIONS)}"
for q in QUESTIONS:
    assert len(q["options"]) == 4, f"{q['id']} must have exactly 4 options"